Task #67506: [User] Tạo bài viết
awesome-academy/hn_python_naitei19-infor_sharing_forum pull request #11
Opened 2023-09-12 16:37 UTC by kawasemi2k1

## Related Tickets
- [Task #67506](https://edu-redmine.sun-asterisk.vn/issues/67506)

## WHAT
- Tạo bài viết

## HOW
- 

## Evidence (Screenshot or Video)

## Notes (Kiến thức tìm hiểu thêm)

2023-09-12 17:00 UTC, tuyenldhust requested changes

2023-09-12 17:00 UTC, ledinhtuyen commented on app/migrations/0002_alter_post_content.py
> +        ('app', '0001_initial'),
Sao không xóa file migration cũ đi, makemigrations lại để ko phải tạo file mới.

2023-09-12 17:06 UTC, kawasemi2k1 commented on app/migrations/0002_alter_post_content.py
> +        ('app', '0001_initial'),
thế thì phải xóa database làm lại ý. Ngại thêm lại quá hicc, chắc ko sao đâu nhở :V

2023-09-13 01:25 UTC, tuyenldhust approved these changes

2023-09-13 04:05 UTC, closed without merging