init model and add relationship
awesome-academy/hn_python_naitei19-infor_sharing_forum pull request #2
Opened 2023-09-06 10:47 UTC by kawasemi2k1

## Related Tickets
- [Task #67488](https://edu-redmine.sun-asterisk.vn/issues/67488)

## WHAT
- init model

## HOW
- Thêm `app.apps.AppConfig` vào `INSTALLED_APPS`
- Tạo các class trong file model tương ứng với các bảng, thêm các thuộc tính và ràng buộc
- Gõ lệnh makemigration và migrate

## Evidence (Screenshot or Video)
![image](https://github.com/awesome-academy/hn_python_naitei19-infor_sharing_forum/assets/86403485/bd6463c8-225e-48d6-adfa-c57c6b494326)

![app_bookmark](https://github.com/awesome-academy/hn_python_naitei19-infor_sharing_forum/assets/86403485/308f3c9b-f3f8-44d8-a7d6-dc3228955e2a)

2023-09-06 10:51 UTC, kawasemi2k1 commented
ready

2023-09-07 01:28 UTC, tuyenldhust requested changes

2023-09-07 01:28 UTC, tuyenldhust commented on app/models.py
> +    user = models.OneToOneField(User, on_delete=models.CASCADE)
Theo bình luận của 
[TesLake](https://www.reddit.com/r/django/comments/yo2w0h/should_i_extend_the_default_user_model/) thì kế thừa class AbstractUser thì ổn hơn hay sao ấy.

2023-09-07 01:31 UTC, huongnt-2545 reviewed
Thành viên trong nhóm review rồi approve trc rồi c mới review nhé

2023-09-07 01:41 UTC, kawasemi2k1 commented on app/models.py
> +    user = models.OneToOneField(User, on_delete=models.CASCADE)
Cơ mà ý Tuyên là thêm thuộc tính mới nhưng vẫn là ở bảng Users (bảng mà Django cung cấp) đúng không? Tớ định tách ra 2 bảng cơ mà chợt nhận ra lúc login cũng cần time_banned nên chắc gộp lại 1 bảng User thôi nhở. Ko để Profile nữa?

2023-09-07 01:54 UTC, tuyenldhust commented on app/models.py
> +    user = models.OneToOneField(User, on_delete=models.CASCADE)
Kế thừa AbstractUser có lẽ ổn hơn, một số chỗ trong trang web tới có chỗ xuất hiện cả username và danh hiệu, thì đỡ phải join bảng

2023-09-07 01:56 UTC, kawasemi2k1 commented on app/models.py
> +    user = models.OneToOneField(User, on_delete=models.CASCADE)
hmm uki để tớ sửa

2023-09-07 02:44 UTC, tuyenldhust approved these changes

2023-09-07 02:48 UTC, tuyenldhust approved these changes

2023-09-07 02:50 UTC, kawasemi2k1 commented
## Related Tickets
- [Task #67488](https://edu-redmine.sun-asterisk.vn/issues/67488)

## WHAT
- init model

## HOW
- Thêm `app.apps.AppConfig` vào `INSTALLED_APPS`
- Tạo các class trong file model tương ứng với các bảng, thêm các thuộc tính và ràng buộc
- Gõ lệnh makemigration và migrate

## Evidence (Screenshot or Video)
![image](https://github.com/awesome-academy/hn_python_naitei19-infor_sharing_forum/assets/86403485/cbbd68ca-c316-4d23-b9eb-4be402717a63)

![app_bookmark](https://github.com/awesome-academy/hn_python_naitei19-infor_sharing_forum/assets/86403485/524f8162-9180-47b4-9662-0cbdca48838f)

2023-09-07 02:51 UTC, kawasemi2k1 commented
ready

2023-09-07 03:37 UTC, huongnt-2545 commented on app/models.py
> +    is_deleted = models.BooleanField(default=False)
2 field này với field `is_violated` e gộp thành 1 field `status`, để data type là integer, set option choices

2023-09-07 03:37 UTC, huongnt-2545 commented on app/models.py
> +    mode = models.IntegerField(default=0)
field `mode` là kiểu private/public đấy hử e?
nên để data type là integer, rồi config thêm option choices 
vd: 0: private, 1: public

2023-09-07 04:18 UTC, kawasemi2k1 commented
ready

2023-09-07 05:58 UTC, tuyenldhust approved these changes

2023-09-07 07:40 UTC, huongnt-2545 approved these changes
merged

2023-09-07 07:40 UTC, merged